### ISSUE TITLE
Code no longer runs

### ISSUE THREAD

**Issue by microbit-mark** [Tinkertanker/pxt-tinkercademy-misc#2]
USer reports that this program used to work 1 month ago and now lo longer works.[microbit-Dr-PLAY(2).hex.zip](https://github.com/Tinkertanker/pxt-tinkercademy-tinker-kit/files/3446426/microbit-Dr-PLAY.2.hex.zip) removing the tinker blocks seems to fix the issue, but I can't get a reliable reproducer. Updating the blocks does not fix the issue either.

**Comment by microbit-mark** [comment]
can you take a look at this @firemansamm @yjsoon ?

**Comment by yjsoon** [comment]
Sorry, missed this. Will take a look. Could be due to the memory issues we faced (and since fixed) with the OLED library.

**Comment by yjsoon** [comment]
@microbit-mark I'm unable to import this hex file, can I trouble you to check / share a link to a hosted version?

**Comment by microbit-mark** [comment]
I think it may have been renamed and so doesn't load. Here's a link https://makecode.microbit.org/_DCtita9ifKED

**Comment by yjsoon** [comment]
Seems to work with the latest version of the extensions, so it was likely the OLED issue. Replicated with latest extension: https://makecode.microbit.org/_gYbVVh8tXR2M. Closing; hopefully the user got it working!

**Comment by yjsoon** [comment]
Thanks @microbit-mark as always 👍
